---

language: generic
dist: trusty
sudo: required

addons:
  apt:
    packages:
      - wget
      - bc
      - build-essential
      - gawk
      - xorriso

services:
  - docker

script:
  - ./minimal.sh
