style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/prologic/minimal-container-linux
options:
  commits:
    filters:
      Type:
        - Added
        - Fixed
        - Documented
  commit_groups:
    title_maps:
      Added: Features
      Fixed: Bug Fixes
      Documented: Documentation
  header:
    pattern: "^((\\w+)\\s.*)$"
    pattern_maps:
      - Subject
      - Type
  notes:
    keywords:
      - BREAKING CHANGE
